name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  version: "3.22.1"
jobs:
  container_build:
    # The host should always be linux
    runs-on: ubuntu-latest
    name: ${{matrix.distro}}-${{matrix.arch}}

    strategy:
      fail-fast: false
      matrix:
        distro:
         - bullseye
        arch:
          - aarch64
          - armv7
          - armv6
          - ppc64le
          - s390x
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Build
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ github.token }}
          setup: mkdir -p "${PWD}/artifacts"
          dockerRunArgs: --volume "${PWD}/artifacts:/artifacts"
          shell: /bin/sh
          install: |
            apt-get update -y
            apt-get install -y build-essential gcc libssl-dev wget

          run: |
            wget https://github.com/Kitware/CMake/releases/download/v${{env.version}}/cmake-${{env.version}}.tar.gz
            tar xf cmake-${{env.version}}.tar.gz
            cd cmake-${{env.version}}
            ./bootstrap
            gmake
            DESTDIR="cmake-${{env.version}}-${{matrix.distro}}_${{matrix.arch}}" make install
            tar -czf cmake-${{env.version}}-${{matrix.distro}}_${{matrix.arch}}.tar.gz cmake-${{env.version}}-${{matrix.distro}}_${{matrix.arch}}/
            mv cmake-*.tar.gz /artifacts/

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: artifacts/cmake[-_]*.*

  release_assets:
    name: Release
    needs: [container_build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Download Files
      uses: actions/download-artifact@v2

    - name: Deploy Package
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
       repo_token: "${{ secrets.DEPLOYTOKEN }}"
       automatic_release_tag: "${{env.version}}"
       prerelease: false
       title: "${{env.version}} Release"
       files: |
         artifact/*
